### ISSUE TITLE
create welcome page

### ISSUE THREAD

**Issue by AndrealHarrison** [MobileApps-Cascadia/pollinator-pathway-ios#1]
https://github.com/MobileApps-Cascadia/pollinator-pathway-ios/issues/1  Create Welcome Page

Create a page to greet new or returning users

DOD Welcome page is complete with logo and welcome text

User X has opened the app and is greeted by a welcome page that entices them to stay, and is used as the start for all other processes in the app.

ASSIGNEE
@asb43

**Comment by asb43** [comment]
https://github.com/MobileApps-Cascadia/pollinator-pathway-ios/issues/1 
#1 Create Welcome Page

Create a page to greet new or returning users

DOD done when the when the welcome page looks like the mock-ups

User X has opened the app and is greeted by a welcome page that entices them to stay, and is used as the start for all other processes in the app.

ASSIGNEE
@asb43

**Comment by asb43** [comment]
Completed finally 5/12/2022
