### ISSUE TITLE
create map page for plantings

### ISSUE THREAD

**Issue by AndrealHarrison** [MobileApps-Cascadia/pollinator-pathway-ios#19]
Description: Create Map page on main tab navigation that links to apple maps API with all plantings currently registered on the PNWPP, displaying accurate location data for Greater Seattle area.

DOD: When clicking the "live maps" navigation button loads a live, up to date map using Apple Maps API. 

User Story: PNWPP member x wants to check to make sure his own planting he recently registered with the pathway is displaying accurately on the apps map page.  He clicks the map tab button and is able to not only view his own planting location on an overlay map of his area, but also see other public planting location information near him.

**Comment by shahinnezam** [comment]
DOD Met, bugs resolved.  Branch has been merged into develop and develop merged into Main.  Closing issue out
