### ISSUE TITLE
Incorporate QR code Scanner functionality into View

### ISSUE THREAD

**Issue by AndrealHarrison** [MobileApps-Cascadia/pollinator-pathway-ios#2]
Create QR code Scanner functionality with actual Capture Session and button.

DOD: When clicking scan QR code button opens AVCaptureSession and uses video capture device to find a QR code and return either working scan, or working scan with bad code, bad scan, or no scan.

User X is a recent new member to the PNWPP.  He opens the app for the first time and sees the welcome page.  His goal is to register his new pollinator box, and then use the app to manage his account.   The registration button works for opening his camera app and allowing him to capture the QR code included in his pollinator kit.

**Comment by shahinnezam** [comment]
COMPLETED last week! just needed a physical device to run it on!
